backend = "wal"
palette = "harddark"
saturation = 10
check_contrast = true

[templates]
kitty = { src='kitty.conf', dst='~/.config/kitty/theme.conf'}
#niri = { src='niri.conf', dst='~/.config/niri/style.kdl'}

